# Welcome to the wonderful world of Python!

## Basics

Lets start of by outputing a string

In [1]:
print('Hello World!')

Hello World!


Now lets define a variable as an integer

In [2]:
my_first_int = 10
type(my_first_int)

int

And now a float

In [3]:
my_first_float = 10.0
print(my_first_float)

10.0


And last a string

In [4]:
my_first_string = 'pythonisthebestthingsinceslicedbread'
print(my_first_string)

pythonisthebestthingsinceslicedbread


Some mathematical operators:

In [5]:
a = 10.0
b = 20.0

c = a + b
print("The value of c is " + str(c))

d = c - a
print("The value of d is " + str(d))

e = a / b
print("The value of e is " + str(e))

f = a**b
print("The value of f is " + str(f))

The value of c is 30.0
The value of d is 20.0
The value of e is 0.5
The value of f is 1e+20


## Arrays

In [6]:
x = [1,3,5,7,9]
print(x)

[1, 3, 5, 7, 9]


In [7]:
print(x[0])

1


In [8]:
print(x[:])

[1, 3, 5, 7, 9]


In [9]:
print(x[2:])

[5, 7, 9]


In [10]:
print(x[:3])

[1, 3, 5]


## Loops

A simple for loop

In [11]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


And a while loop

In [12]:
count = 0
while (count < 10):
    print(count)
    count = count + 1

0
1
2
3
4
5
6
7
8
9


## Conditionals

In [13]:
numbers = [1,2,3,4,5,6]

for x in numbers:
    if(x % 2 == 0):
        print(str(x) + " is even")
    else:
        print(str(x) + " is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even


## References

As all objects in python are by reference, we quickly have a look at how this affects us:

In [14]:
x = [1,2,3,4,5]
y = x
x.append(7)
print(y)

[1, 2, 3, 4, 5, 7]


In [15]:
x = [1,2,3,4,5]
y = x[:] # slice the list, makes a copy of the array
x.append(7)
print(y)

[1, 2, 3, 4, 5]


## Functions

In [35]:
def add(a,b):
    c = a + b
    return c

print("The results of 1 + 2 = " + str(add(1,2)))

The results of 1 + 2 = 3


## NumPy

Modules are imported using the "import" statement in python

In [16]:
import numpy as np

Numpy is now imported in the local namespace as np, lets check the version number

In [17]:
print(np.__version__)

1.10.4


NumPy has many functions of which most we will not use. We will try to give you a introduction to some of the most commonly used ones

In [18]:
x = np.zeros([10,10])

In [19]:
print(x)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [20]:
print(x.shape)

(10, 10)


Define a equally spaced array

In [21]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [22]:
x = np.linspace(2.0, 3.0, num=5)
print(x)

[ 2.    2.25  2.5   2.75  3.  ]


Multiply with a scalar

In [23]:
y = x * 5
print(y)

[ 10.    11.25  12.5   13.75  15.  ]


Define a matrix

In [24]:
a = np.matrix([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


Matrix multiplication

In [25]:
b = a*a
print(b)

[[ 7 10]
 [15 22]]


Elementwise multiplication

In [26]:
b = np.multiply(a,a)
print(b)

[[ 1  4]
 [ 9 16]]


Sum along axis 0,1 and all

In [27]:
print(np.sum(a, axis=0))

[[4 6]]


In [28]:
print(np.sum(a, axis=1))

[[3]
 [7]]


In [29]:
print(np.sum(a))

10


Now, lets transpose a matrix

In [30]:
a = np.ones([10,4,2])
print(a.shape)

(10, 4, 2)


In [31]:
print(a.transpose().shape) #no axes argument reverses the order of the axis

(2, 4, 10)


In [32]:
print(a.transpose(1,0,2).shape)

(4, 10, 2)
